### ISSUE TITLE
[suggestion] `tapify` should create positional args for signatures w/ positional-only params

### ISSUE THREAD

**Issue by baodrate** [swansonk14/typed-argument-parser#100]
Currently, the `tapify` interface creates "options"/flags (`--` prefixed, position-agnostic arguments) for each parameter in the function signature. e.g.:

```python
from tap import tapify
def foo(num1: int, num2: float, /, bar: str) -> None:
    ...

if __name__ == "__main__":
    tapify(foo)
```

produces:

```
usage: ... [-h] --num1 NUM1 --num2 NUM2 --bar BAR

options:
  -h, --help   show this help message and exit
  --num1 NUM1  (int, required)
  --num2 NUM2  (float, required)
  --bar BAR    (str, required)
```

Since parameters that follow `/` are [positional-only](https://peps.python.org/pep-0570/), `tapify` should omit the `--` prefix when it calls `add_argument(...)`, so that `argparse` creates a positional argument.

**Comment by kddubey** [comment]
`tapify` currently doesn't work when there are positional-only arguments.

For example, try to run your script (instead of just `-h`)

```zsh
$ python script.py --num1 1 --num2 2 --bar "bar"
Traceback (most recent call last):
  File "/Users/kdubey/projects/typed-argument-parser/script.py", line 16, in <module>
    tapify(foo)
  File "/Users/kdubey/projects/typed-argument-parser/tap/tapify.py", line 335, in tapify
    return class_or_function(**command_line_args_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: foo() got some positional-only arguments passed as keyword arguments: 'num1, num2'
```

I'll fix this bug

**Comment by martinjm97** [comment]
Hi @baod-rate, 

I didn't know about this feature. Thank you for raising this issue. I agree that this is a bug and that it should be addressed. @kddubey thank you very much for offering to fix it! 

--Jesse

**Comment by martinjm97** [comment]
Thank you @kddubey for the fix!

--JK
