### ISSUE TITLE
Add useful type hints to `Tap.add_subparsers`

### ISSUE THREAD

**Issue by aucampia** [swansonk14/typed-argument-parser#110]
Currently, the type signature is just `def add_subparsers(self, **kwargs) -> None:` and this more or less eliminates all benefits of type hints, and then some. It would be much better if this function actually had accurate type hints.

**Comment by swansonk14** [comment]
Hi @aucampia,

Thank you for bringing up this issue! We believe this is similar to https://github.com/swansonk14/typed-argument-parser/issues/69.

Best,
Jesse and Kyle
