### ISSUE TITLE
Versions should not be compared as strings

### ISSUE THREAD

**Issue by ChristosSpyropoulos** [swansonk14/typed-argument-parser#134]
Hi guys. Great work on your project.
I just wanted to point out that comparing versions like this:
`_IS_PYDANTIC_V1 = pydantic.__version__ < "2.0.0"`
will break some time.
for example:
```
>>> "10.0" > "2.0"
False
```
I found it in 3 different places.
Thank you all for doing a great job.

**Comment by kddubey** [comment]
My bad. Thank you for finding and reporting this :-)
