### ISSUE TITLE
tapify input description manually

### ISSUE THREAD

**Issue by kddubey** [swansonk14/typed-argument-parser#138]
Currently, `tapify` always gets the script description for `-h` from the docstring of the input.

When the input is a class, its docstring usually doesn't tell you what the script is going to do. The class usually represents data that's inputted to a function/method.

The user should be able to pass in a description manually through a new kwarg in `tapify`, `description`, which defaults to the current behavior: get the description from the input's docstring.

I'll submit a PR for this in a few days or weeks in case no else gets to it

**Comment by martinjm97** [comment]
I agree it would be helpful to add the ability to manually provide a description that overrides the docstring. A PR would be greatly appreciated!

--Jesse
