### ISSUE TITLE
Warning during installation when `wheel` isn't installed

### ISSUE THREAD

**Issue by kddubey** [swansonk14/typed-argument-parser#141]
I've been installing this package in a linux instance where I had to manually install python and pip.
Looks like `wheel` doesn't get installed, so I get this inconsequential warning:

```
  DEPRECATION: typed-argument-parser is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for typed-argument-parser ... done
```

Are you open to replacing `setup.py` with `pyproject.toml`? The latter has some [advantages](https://peps.python.org/pep-0621/). If so, I'll have a PR ready soon :-)

**Comment by martinjm97** [comment]
Yes, after reading PEP 621 and some of [these answers](https://stackoverflow.com/questions/62983756/what-is-pyproject-toml-file-for),  I'm convinced that everything that can be statically defined in a `pyproject.toml` should be there. 

Thank you for your expertise!
