### ISSUE TITLE
Multi line comments as help string?

### ISSUE THREAD

**Issue by rggjan** [swansonk14/typed-argument-parser#15]
Is there a way to support multi-line comments as help string? For really long, descriptive help strings, it would be useful to be able to split them up...

**Comment by martinjm97** [comment]
It is supported through the `add_arguments` method. For example,
```
class T(Tap): 
    arg: int = 7 
    def add_arguments(self): 
        self.add_argument('--arg', help=("This is a long long " 
            "string so so long that it needs many lines")) 
```
The help string is then:
```
usage: ipython3 [--arg ARG] [-h]

optional arguments:
  --arg ARG   This is a long long string so so long that it needs many lines
  -h, --help  show this help message and exit
```

**Comment by rggjan** [comment]
I see. Would it be possible to support multi line comments in addition, or do you think this is not needed / too complicated? Since for just getting a longer help text, this complicates things a lot (almost to the level where just using argparser natively makes sense...)

**Comment by martinjm97** [comment]
Thanks again for the interest. You have a good point. One potential option would be to have a PR for a specific feature to support multiline comments like
```
class T(Tap): 
    arg1: int = 7 # My comment
    # spans many lines
    arg2: int = 2 # My other comment doesn't
``` 
I don't think that the change above would be particularly difficult to implement, but I'm a little concerned that it is less intuitive. Would you be satisfied with this? Do you have alternate recommendations?

To give you a little history on our thinking around this topic, we originally were going to use the docstring for generating the help string. We decided against this because it would be cumbersome for objects with many attributes--source code navigation brings you to the the line where the object is defined, not to the docstring.

**Comment by rggjan** [comment]
Thanks @martinjm97 for looking into this.

Yes, I see that this could be less intuitive, especially in a case like this, where you want to have actual comments intermixed with the argparse-help comments:
```
class T(Tap): 
    # video arguments
    video_arg1: int = 7 # Comment to video_arg1
    # audio arguments
    audio_arg1: int = 2 # Comment to audio_arg1
    audio_arg2: int = 2 # Comment to audio_arg2
```

I also agree that the comment solution is pretty elegant compared to the docstring. Maybe a solution would be to only consider multi-line comments which have the same indendation as the first line:

```
class T(Tap): 
    # This is just a comment
    video_arg1: int = 7 # This is video_arg1 help which
                        # continues on this line 
    # Again a normal comment
    ...
```

This strikes me as still pretty intutive both for the functionality and for good code readibility.

**Comment by martinjm97** [comment]
I like the proposal, but I think this introduces some friction with a number of the Python code style rules. I'm pretty sure that in most cases it's impossible to satisfy all of them with this sort of multi-line comment. I get errors like: 
```
indentation is not a multiple of four (comment) pycodestyle(E114)
unexpected indentation (comment) pycodestyle(E116)
at least two spaces before inline comment pycodestyle(E261)
```
An alternative is to use standard Python multi-line comments:
```
class T(Tap):
    arg1: bool = True  '''Hello World
                                    this continues '''
    my_otherparam: int = 1
```
It's not pretty, but I think it doesn't violate any Python style rules.

**Comment by rggjan** [comment]
I think your example with the multi-line comment doesn't work. I get a `SyntaxError: invalid syntax` when trying to run your example...

Another option would be this:
```
class T(Tap): 
    # This is just a comment
    video_arg1: int = 7 # This is video_arg1 help which
    #                     continues on this line 
    # Again a normal comment
    ...
```
but is also not very pretty...

Or we could add a rule to your original proposal to only span lines until there is a newline:

```
class T(Tap): 
    # This is just a comment
    video_arg1: int = 7 # This is video_arg1 help which
    # continues on this line 

    # Again a normal comment
    ...
```

What do you think?

**Comment by rggjan** [comment]
(Also, should we re-open this issue since it is under consideration again?)

**Comment by swansonk14** [comment]
Another option which fixes the syntax error from earlier is this:

```python
from tap import Tap

class T(Tap):
    arg1: bool = True  # this is the one-line summary
    """
    This is the multiline explanation
    """
    my_otherparam: int = 1
```

This design could be good since it simultaneously allows for single and multiline comments. What do you think?

I'm going to reopen the issue since multiline comments are a good idea worth implementing, but it may be a little while before we are able to fully implement this feature.

**Comment by rggjan** [comment]
Nice idea! Yes I think this is better than my proposal 👍

**Comment by zmh908264302** [comment]
@martinjm97 Could you consider another thing about muti-line comments when I want pass variable,
e.g.

class MyTap(Tap):
    var = ["a", "b"]
    info: str = "test"  
    """
        This is info about: {}
    """.format(",".join(var))

**Comment by zmh908264302** [comment]
@martinjm97 Could you consider another thing about muti-line comments when I want pass variable,
e.g.
```
class MyTap(Tap):
	var = ["a", "b"]
	info: str = "test"
	"""
		This is info about: {}
	""".format(",".join(var))
```

**Comment by martinjm97** [comment]
@zmh908264302 Definitely an interesting idea, but I'd like to see a more realistic use-case. I think of help strings as pretty static. For example, docstrings do not support format strings (without hacks).

**Comment by swansonk14** [comment]
See this release for the implementation: https://github.com/swansonk14/typed-argument-parser/releases/tag/v_1.5.3. Thanks again for the great suggestion @rggjan!

**Comment by rggjan** [comment]
Awesome, thanks a lot!
