### ISSUE TITLE
Once Python 3.8 is deprecated change the type typing

### ISSUE THREAD

**Issue by martinjm97** [swansonk14/typed-argument-parser#154]
We currently use `typing.Type`. After Python 3.8 is deprecated, we should use the built-in `type` for type-hinting instead of `Type` as per https://peps.python.org/pep-0585 for code quality.

**Comment by swansonk14** [comment]
Solved by da7b4de6017df8a043ec45aa9a72c3dda0e789e7

**Comment by swansonk14** [comment]
Solved by ee914c0725374b14a095d44f50d634d923ab0fbc
