### ISSUE TITLE
Implement a way to load a saved Tap from a file

### ISSUE THREAD

**Issue by martinjm97** [swansonk14/typed-argument-parser#20]
Tap currently supports a `save` function but doesn't have a way to load from a saved file. Similarly, one can convert a Tap to a dict using `as_dict`. It would be helpful to be able to create a Tap using something like a `from_saved` and `from_dict`.

**Comment by swansonk14** [comment]
Implemented in https://github.com/swansonk14/typed-argument-parser/releases/tag/v_1.4.2
