### ISSUE TITLE
Should Tap parse the default values for Set, Tuple types?

### ISSUE THREAD

**Issue by swansonk14** [swansonk14/typed-argument-parser#28]
Tap tries to parse values for arguments of Set and Tuple types into sets and tuples. This is fine when the arguments are provided on the command line as they must conform to the structure of a set or a tuple, but this parsing also occurs for the default value if a value isn't provided on the command line. Again, this is fine if the default value is in fact a set or a tuple (or even a related object like a list), but it's problematic when the default value is unrelated, e.g., if the default value is `None`. See the example below:

```python
from typing import Set, Tuple

from tap import Tap


class Args(Tap):
    arg_tuple: Tuple[str, ...] = None
    arg_set: Set[str] = None


args = Args().parse_args([])  # Crash!
```

```
Traceback (most recent call last):
  File "blah.py", line 11, in <module>
    args = Args().parse_args([])
  File "/Users/kyleswanson/typed-argument-parser/tap/tap.py", line 318, in parse_args
    value = tuple(value)
TypeError: 'NoneType' object is not iterable
```

This manual parsing into sets and tuples must be changed so that it only applies to arguments provided on the command line and not to default arguments.

**Comment by martinjm97** [comment]
Added functionality in release: [v1.5.1](https://github.com/swansonk14/typed-argument-parser/releases/tag/v_1.5.1)
this allows for defaults arguments that are not parsed as a list.
