### ISSUE TITLE
How to tell which subparser was called?

### ISSUE THREAD

**Issue by anniecherk** [swansonk14/typed-argument-parser#33]
Is there a way to find out which subparser was called?

For example, here's an example with two subparsers for `git add` and `git commit`:

```
class GitAddParser(Tap):
    verbose: bool = False
    patch: bool = False

class GitCommitParser(Tap):
    verbose: bool = False
    author: Optional[str] = None

class GitParser(Tap):
    version: bool = False

    def configure(self):
        self.add_subparsers(help='sub-command help')
        self.add_subparser('add', GitAddParser, help='git add help')
        self.add_subparser('commit', GitCommitParser, help='git commit help')

args = GitParser().parse_args()

# if the command was `git add` do some logic
# TODO
# elif the command was `git commit` do some other logic
# TODO
```

I want to do different things based on which subparser was called, but I can't tell where / if that information is being stored when `parse_args`  is called.

If that information isn't being tracked, I can see two ways to work around this but they both have drawbacks. 

One way is to check whether `args` has a field name that is unique to only one subparser; ie, if `args.author` is defined in the above example, the command must have been `commit`. This seems dangerous because it's entirely possible that in the future the code changes so that another subparser has a field with the same name.

The other way is I can see is to modify all subparsers to have an explicit field which tracks which command they represent:
```
class GitAddParser(Tap):
    verbose: bool = False
    patch: bool = False
    command: str = "add"

class GitCommitParser(Tap):
    verbose: bool = False
    author: Optional[str] = None
    command: str = "commit"
```
However, this is also not a great solution because then `command` is a field which can be changed when invoking the parser, which shouldn't be the case. 

Is there a better way to tell which subparser was called?

**Comment by martinjm97** [comment]
Hi @anniecherk, 

Thank you for the carefully worked example. If I understand it correctly, this has been [solved for argparse](https://stackoverflow.com/questions/4575747/get-selected-subcommand-with-argparse) and as a wrapper for argparse, Tap supports the same functionality. Here's a worked example:
```python
class SubparserA(Tap):
     bar: int  # bar help
 
class SubparserB(Tap):
     baz: Literal['X', 'Y', 'Z']  # baz help
 
class Args(Tap):
     foo: bool = False  # foo help

     def configure(self):
         self.add_subparsers(help='sub-command help', dest="subparser_name")
         self.add_subparser('a', SubparserA, help='a help')
         self.add_subparser('b', SubparserB, help='b help')
         
args = Args().parse_args(['a', '--bar', '1'])

print(args.subparser_name)  # The result is "a"
```

Let me know if this resolves the issue :).

**Comment by anniecherk** [comment]
Ah, perfect, yes that's exactly what I was looking for! I didn't realize I could use the argparse keyword but that makes a lot sense. Thanks very much!

**Comment by martinjm97** [comment]
Glad it worked out! Happy tapping!

**Comment by mo22** [comment]
Hey, great project! I did something similar a while back and solved the subparser issue by using something like this:
```
    class Args(Command):
        verbose = Argument(bool)
        cmd = Subcommands(Union[
            ArgsListZones,
            ArgsGetNameservers,
            ArgsDeleteZone,
            ArgsExportZone,
            ArgsImportZone,
            ArgsImportYml,
            ArgsPurgeYml,
        ])
```
this way the selected command could be checked by python idioms and would also have the correct typings

**Comment by mo22** [comment]
also a `@tap.Positional` decorator might make `configure` not needed so often

**Comment by ethanabrooks** [comment]
@mo22 could you define those `Command` and `Subcommands` classes for us? Trying to come up with something that plays a little better with the Pyright linter.
