### ISSUE TITLE
Process_args not called in from_dict

### ISSUE THREAD

**Issue by rubencart** [swansonk14/typed-argument-parser#41]
Title explains itself, I believe it would make sense to call `process_args()` in `from_dict`, like it is called in `parse_args`, or am I missing something?

**Comment by rubencart** [comment]
If calling `process_args()` in `from_dict` is **not** the wanted behavior, I would clarify this in the documentation :-).

**Comment by martinjm97** [comment]
Hi @rubencart,

Interesting, at this point, adding `process_args` to `from_dict` is a breaking change. The case for not having `process_args` in `from_dict` is that sometimes `from_dict` can be a mechanism to swap out particular arguments and `process_args` could introduce problematic mutation. 

That said, our documentation is unclear about this and we'll update it to clarify this issue. Thank you for bringing this issue up!

Best, 
Kyle and Jesse

**Comment by rubencart** [comment]
Mmm yes I understand! 

Apart from updating the docs, perhaps we could add an argument to `from_dict`, to choose whether to call `process_args` or not? Or, alternatively, maybe we could add a different method to Tap, `init_from_dict` or `build_from_dict` or `parse_from_dict`, that not only copies the args from the dict but also fully initializes the Tap instance (like calling `process_args` etc.)? This would be something like the dict counterpart of `parse_args` then?

This is not a big issue of course, you can always just call `process_args` yourself. But in a way it feels not 100% intuitive to me that `from_dict` does set `self._parsed = True`, suggesting this can be the method you use to fully prepare the Tap instance for use, but that it doesn't call `process_args`. If, like you say, you want to use `from_dict` just to swap out arguments, doesn't it make more sense *not* to set `self._parsed` then?

**Comment by martinjm97** [comment]
Hi @rubencart,

I see how it may seem unintuitive that `from_dict` sets `self._parsed = True`, however, in conjunction with the `as_dict` method its behavior becomes intuitive. The idea is that `as_dict` is defined on already parsed `Tap`s and as a result the values specified in a dictionary passed to `from_dict` are expected to be values for the post-`process_args` arguments. For example, consider the case of `copy_of_args = Args().from_dict(args.as_dict())`.

We're torn on whether an `init_from_dict` that calls `process_args` makes sense. In terms of code, as you said, just calling `from_dict` then `process_args` is sufficient. Is this adding API bloat or exposing a useful feature?  Either way, this is interesting to think about!

Thanks, 
Kyle and Jesse

**Comment by rubencart** [comment]
Mmm yes as long as it's clearly documented it is not such a big deal to just call `process_args` yourself :).

> I see how it may seem unintuitive that from_dict sets self._parsed = True, however, in conjunction with the as_dict method its behavior becomes intuitive. The idea is that as_dict is defined on already parsed Taps and as a result the values specified in a dictionary passed to from_dict are expected to be values for the post-process_args arguments. For example, consider the case of copy_of_args = Args().from_dict(args.as_dict()).

I see. My use case involves loading arguments from another, arbitrary python dict. In that case, whether you'd have to call `process_args` depends on the dict, so in any case I agree that it would not be a good idea to always call `process_args` in `from_dict`. But I do wonder, what is the difference then between something like `copy_of_args = Args().from_dict(args.as_dict())` and just copying the Config object? If there is none, API-wise, it would be more intuitive to me to define this behavior in a `copy` function or so, and the behavior that I'm talking about, where you load in arguments from an external dict and *not* another Tap config, in `from_dict`...

**Comment by martinjm97** [comment]
We've found that users of `argparse` often use `copy_of_args = deepcopy(args)`.  `Tap` objects can be copied in the same way! This is the API for copying at this point. Happy to revise it if it's deficient. Note that `Args().from_dict(args.as_dict())` is a shallow copy rather than a deep copy.

**Comment by martinjm97** [comment]
This issue seems to be resolved. Happy to reopen if we're mistaken. 

--Jesse and Kyle
