### ISSUE TITLE
Unsupported Operation

### ISSUE THREAD

**Issue by daverdude** [swansonk14/typed-argument-parser#44]
writer.writerow(header)
io.UnsupportedOperation: Not Writable

Any help clearing this issue would be appreciated

**Comment by martinjm97** [comment]
I'm a little confused. How is Tap involved here?

**Comment by daverdude** [comment]
import csv
from rdkit import Chem

from tap import Tap  # pip install typed-argument-parser (https://github.com/swansonk14/typed-argument-parser)


class Args(Tap):
    data_path: str  # Data CSV to sanitize
    save_path: str  # Path to CSV where sanitized data will be saved


def sanitize(data_path: str, save_path: str):
    with open(data_path) as f:
        reader = csv.reader(f)
        header = next(reader)
        lines = [line for line in reader if line[0] != '' and Chem.MolFromSmiles(line[0]) is not None]

    with open(save_path) as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for line in lines:
            writer.writerow(line)


if __name__ == '__main__':
    args = Args().parse_args()

    sanitize(args.data_path, args.save_path)

**Comment by martinjm97** [comment]
I'm pretty sure `with open(save_path) as f` should be `with open(save_path, 'w') as f` because you're writing to that file. The bug is that it only had default permissions. I think this bug is independent of Tap.

**Comment by daverdude** [comment]
Interesting, i must have misunderstood the application of Tap within this context. Thanks for the help!

**Comment by martinjm97** [comment]
It's just for argument parsing :). Happy tapping and good luck!
