### ISSUE TITLE
`underscores_to_dashes` should not apply to required positional arguments

### ISSUE THREAD

**Issue by jakkes** [swansonk14/typed-argument-parser#50]
Required positional arguments cannot (in `argparse`) be given a name including `-`. These require `_`. Thus, using TAP, it is currently not possible to run with underscores on required positional arguments, and dashes on optional keyword arguments.

**Comment by martinjm97** [comment]
Hi @jakkes,

Great find!  Does https://github.com/swansonk14/typed-argument-parser/commit/f30ffbe46aa08a68aa84f8edd6062fa9e69eea68 resolve this?

Thanks, 
Kyle and Jesse

**Comment by jakkes** [comment]
Looks like it.
