### ISSUE TITLE
Feature request: Allow pickling / unpickling

### ISSUE THREAD

**Issue by phiresky** [swansonk14/typed-argument-parser#52]
I'm trying to pass a Tap object with to a different thread / process, but it's failing with `AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'`

The following seems to work:

```py
class Args(tap.Tap):
    runs: List[str]
    mean: Literal["median", "mean"] = "median"
    # ....

    def __getstate__(self):
        return self.as_dict()

    def __setstate__(self, d):
        self.__init__()
        self.from_dict(d)
```

Seems like this could be included in the library?

**Comment by swansonk14** [comment]
Hi @phiresky,

Thank you for bringing up the issue and for suggesting the solution! We think this looks great so we implemented it in this commit: https://github.com/swansonk14/typed-argument-parser/commit/5b2eab67473a90e05d1ed5d2397914a5f33d1f9e

Thanks!
Jesse and Kyle
