### ISSUE TITLE
`underscore_to_dashes` isn't propagated to subparsers

### ISSUE THREAD

**Issue by pmiddend** [swansonk14/typed-argument-parser#53]
My example is:

```
class AddProposal(Tap):
    proposal_id: int

class Arguments(Tap):
    def configure(self) -> None:
        self.add_subparsers(dest="subparser_name")

        self.add_subparser(
            "add-proposal",
            AddProposal,
            help="Add a new proposal",
        )

args = Arguments(underscores_to_dashes=True).parse_args()
```

Typing `python myapp.py add-proposal --help` I get `proposal_id` as an argument

**Comment by swansonk14** [comment]
Hi @pmiddend,

Thank you for bringing up the great issue! We agree that this is a problem, and we made a fix to propagate the `underscores_to_dashes` value to subparsers in this commit: https://github.com/swansonk14/typed-argument-parser/commit/1c2c0f51ef1f1d4d80b38b9074f88ac868354936

Please let us know if this solves your problem or if you have any other suggestions!

Best,
Kyle and Jesse

**Comment by cardoso-neto** [comment]
I tested on my app and it indeed works. This can be closed.
