### ISSUE TITLE
Document pathlib support

### ISSUE THREAD

**Issue by bartMarinissen** [swansonk14/typed-argument-parser#56]
I figured having pathlib `Path` type support would be nice.

I decided to fork to add the support. After some digging I decided I would add a test. Turns out, there already are tests for this, and they pass.

Since this is a  cool feature, might want to add it to the `Readme.md`.

**Comment by martinjm97** [comment]
Hi @bartMarinissen,

Great point. It's updated as of https://github.com/swansonk14/typed-argument-parser/commit/b96be4e903cdacae6c518f8b0dbb8f866e6f8ec1.

Thanks, 
Jesse
