### ISSUE TITLE
Adding support for subparsers

### ISSUE THREAD

**Issue by svenstaro** [swansonk14/typed-argument-parser#6]
First of all this is a great project and I love the direction it's taken! 

Now, my question is how to basically do argparse's subparsers using tap?

**Comment by martinjm97** [comment]
We do support a notion of "subparsers." It works with standard subclassing. We have an example from our documentation https://github.com/swansonk14/typed-argument-parser#subclassing. 

A child Parser will have all of the methods and attributes as its parent. In contrast to how inheritance with attributes works in Python normally, changing the value of an attribute in a child class will not change the value in the parent class.

**Comment by svenstaro** [comment]
Just revisiting this. I'm afraid I don't understand. I tried the Subclassing example but I can't figure out how to present the subclasses as top level options. Consider `git` where you have `git add`, `git reset`, etc. I want to define those commands `add` and `reset` all on my main `git` program. How would I do this using TAP?

Using the example, I have

```
from tap import Tap
from typing import List

class BaseTap(Tap):
    package: str
    is_cool: bool

    def process_args(self):
        if self.package == 'Tap':
            self.is_cool = True


class StarsTap(BaseTap):
    stars: int


class AwardsTap(BaseTap):
    awards: List[str]


if __name__ == "__main__":
    BaseTap().parse_args()
```

but that only gives me

```
poetry run python lol.py -h
usage: lol.py --package PACKAGE --is_cool [-h]

optional arguments:
  --package PACKAGE  (str, required)
  --is_cool          (bool, required)
  -h, --help         show this help message and exit
```

I'm not presented with the subclassed commands in here.

**Comment by martinjm97** [comment]
I think the confusion is with the behavior of inherited class. Consider changing the last line of your program from `BaseTap().parse_args()` to `AwardsTap().parse_args()`. This produces
```
usage: test.py --awards [AWARDS [AWARDS ...]] --package PACKAGE --is_cool [-h]

optional arguments:
  --awards [AWARDS [AWARDS ...]]
                        (List[str], required)
  --package PACKAGE     (str, required)
  --is_cool             (bool, required)
  -h, --help            show this help message and exit
```
So the inherited class has all of the properties of its parent. The parent remains unchanged. Does this make sense?

**Comment by svenstaro** [comment]
Sure, that part works, but I want something like `git add` with its own set of options and `git reset` with its completely own set of options. So you have something like `git <command> [<args>]` that I don't see how I can build it with TAP.

**Comment by martinjm97** [comment]
We are working adding support for `argparse` subparsers. If you're interested, check out
https://github.com/swansonk14/typed-argument-parser/pull/16
There's still a bit of work to do though. 

I think this should work well for your case.

**Comment by martinjm97** [comment]
Hi all, 

It's been ages since this issue was brought up, but we now have a few plausible ideas. We're conflicted on what the API should be. In argparse, the API is:
```python
parser = argparse.ArgumentParser(prog='PROG')
parser.add_argument('--foo', action='store_true', help='foo help')
subparsers = parser.add_subparsers(help='sub-command help')

# create the parser for the "a" command
parser_a = subparsers.add_parser('a', help='a help')
parser_a.add_argument('bar', type=int, help='bar help')

# create the parser for the "b" command
parser_b = subparsers.add_parser('b', help='b help')
parser_b.add_argument('--baz', choices='XYZ', help='baz help')

# Parse the arguments
args = parser.parse_args()
```
See [argparse subparsers](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_subparsers).
Here are our three top options:

```python
class SubparserA(Tap):
    bar: int  # bar help

class SubparserB(Tap):
    baz: Literal['X', 'Y', 'Z']  # baz help

class Args(Tap):
    foo = True  # foo help

    def new_subparsers(self):
        self.add_subparsers(help='sub-command help')
        self.add_subparser('a', SubparserA, help='a help')
        self.add_subparser('b', SubparserB, help='b help')

args: Union[Args, SubparserA, SubparserB] = Args(prog='PROG').parse_args()
```

```python
class SubparserA(Tap):
    bar: int  # bar help

class SubparserB(Tap):
    baz: Literal['X', 'Y', 'Z']  # baz help

class Args(Tap):
    foo = True  # foo help

    def new_subparsers(self):
        subparsers = {
            'a': {'class': SubparserA, 'help': 'a help'}, 
            'b': {'class': SubparserB, 'help': 'b help'}},
        } 
        self._new_subparsers(subparsers=subparsers, help='sub-command help')

args: Union[Args, SubparserA, SubparserB] = Args(prog='PROG').parse_args()
```

```python
class SubparserA(Tap):
    bar: int  # bar help

class SubparserB(Tap):
    baz: Literal['X', 'Y', 'Z']  # baz help

class Args(Tap):
    foo = True  # foo help
    _subparsers = {
        'a': {'class': SubparserA, 'help': 'a help'}, 
        'b': {'class': SubparserB, 'help': 'b help'}},
    } 
    _subparsers_kwargs = {'help': 'sub-command help'}

args: Union[Args, SubparserA, SubparserB] = Args(prog='PROG').parse_args()
```

We'd love to hear what you think of these or if you have ideas for other interfaces. We have already implemented the first option, which you can see [here](https://github.com/swansonk14/typed-argument-parser/tree/subparsers).

**Comment by luizribeiro** [comment]
How would you implement options 2 or 3 in a way that it's type safe? Wouldn't you need `typing.TypedDict` from Python 3.8?

Feels like option 1 is better in that sense. I also feel like the API is a bit cleaner IMO. Though I would probably not call it `new_subparsers` but something like `add_subparsers` for consistency with `add_arguments`.

Also, is there any reason why we need more than one method to setup the parser? We already seem to have `add_arguments`, why not just have a single method that you can override to configure the parser? For example, `configure` and then you just make whatever calls you need from it to setup arguments, subparsers, etc.

**Comment by martinjm97** [comment]
Hi @luizribeiro, 

Thank you for the feedback and insight. We agree with you. Something like option 1 in a `configure` method seems to be the cleanest option. In more detail:

>How would you implement options 2 or 3 in a way that it's type safe? Wouldn't you need `typing.TypedDict` from Python 3.8?

`TypedDict` is a nice way to type check for options 2 and 3, but I think that it's a reflection that options 2 and 3 are inelegant. Specifically, for both 2 and 3, the user would have to use `TypedDict` to type the appropriate parameters to ensure type safety.

>Though I would probably not call it `new_subparsers` but something like `add_subparsers` for consistency with `add_arguments`.

We agree in so far as it would be nice to be consistent with argparse. Unfortunately, the behavior `add_subparsers` in `argparse` is different than our desired behavior because in order to type the subparser it must declared statically. If we were to override `add_subparsers` then we'd hide a potentially useful `argparse` function and potentially confuse users by overriding a function and having a different signature.

>For example, `configure` and then you just make whatever calls you need from it to setup arguments, subparsers, etc.

Yes, a `configure` method would solve this problem nicely and provide a clean interface. Seems like our best option! We'd then slowly deprecate `add_arguments`.

**Comment by martinjm97** [comment]
The implementation with `configure` and option 1 is [here](https://github.com/swansonk14/typed-argument-parser/tree/subparsers). Everything is ready apart from the tests :)

**Comment by swansonk14** [comment]
The implementation of subparsers is now complete! See release 1.6.0 here:  https://github.com/swansonk14/typed-argument-parser/releases/tag/v_1.6.0
