### ISSUE TITLE
How do you make mutually exclusive groups?

### ISSUE THREAD

**Issue by nacitar** [swansonk14/typed-argument-parser#63]
This subclasses argparse's own ArgumentParser, and the method for adding mutually exclusive groups remains.  You can, in fact, use this without issue... however you cannot use that while also specifying the variable inside the TAP class.  If you do specify the variable in the class, and then also specify it via add_argument, it will fail with something like:
```
argparse.ArgumentError: argument -f/--flag: conflicting option string: --flag
```
You can of course omit the variable from the class... but then you don't get the type hints on the value.  What is the right approach?

**Comment by alanwilter** [comment]
Why is it closed? I'm having the same issue here!
