### ISSUE TITLE
Consistent behavior for the new '|' operator on types for Python 3.10 

### ISSUE THREAD

**Issue by martinjm97** [swansonk14/typed-argument-parser#64]
## Problem
Tap has inconsistent behavior when an argument is typed with `Union[int, float]` versus `int | float`. The current behavior in Case 1 is unhelpful because Tap always tries to cast arguments using first type in the union (in this case, int). An improvement would be to tell the user to specify a type function as in Case 2. We have a similar concern for Case 3. Luckily, Case 2 and Case 4 are consistent and implement the expected behavior.

Common header:
```python
from tap import Tap
from typing import Union


def to_number(string: str):
    return float(string) if '.' in string else int(string)

```

Case 1 (`Union` without configure):
```python
class Py39Tap(Tap):
    number: Union[int, float]

args = Py39Tap().parse_args()
print(type(args.number), args.number)  # error: argument --number: invalid int value: '7.0'
```

Case 2 (`Union` with configure):
```python
class Py39TapWithConfig(Tap):
    number: Union[int, float]

    def configure(self):
        self.add_argument('--number', type=to_number)

args = Py39TapWithConfig().parse_args()  
print(type(args.number), args.number)  # <class 'float'> 7.0
```

Case 3 (`|` without configure):
```python
class Py310Tap(Tap):
    number: int | float

args = Py310Tap().parse_args()
print(type(args.number), args.number)  # ValueError: int | float is not callable
```

Case 4 (`|` with configure):
```python
class Py310TapWithConfig(Tap):
    number: int | float

    def configure(self):
        self.add_argument('--number', type=to_number)

args = Py310TapWithConfig().parse_args()
print(type(args.number), args.number)  # <class 'float'> 7.0
```

## Solution
Change the error handling for both `Union` and `|`. If there is not an explicit typing function specified for `Union`, it should throw an error. Both `Union` and `|` should throw the same error in Cases 1 and 3 that recommends that the user manually define a type function in `configure`.

**Comment by swansonk14** [comment]
This is implemented in https://github.com/swansonk14/typed-argument-parser/pull/66 and is available in Tap version 1.7.2 (release notes here: https://github.com/swansonk14/typed-argument-parser/releases/tag/v_1.7.2).
