### ISSUE TITLE
can I give tap a parser description??

### ISSUE THREAD

**Issue by Moreh-LeeJunhyeok** [swansonk14/typed-argument-parser#74]
Hi.  
I am trying to change old codes to TAP. 
However, it seems that tap does not have description like argparser.
For example
`parser = ArgumentParser(description='this is a sample parser')`
Does tap has parser description?
plus, metavar option and shortcuts like this 
`parser.add_argument(
        '--very_long_arg',
        '-a',
        type=int,
        default=1,
        metavar='N',
        help='it is a very long argument,
    )`

**Comment by wj-Mcat** [comment]
After review the code of `Tap`, there is no description for argparser, so we will add it by myself with the following code:

```python
from sqlalchemy import desc
from tap import Tap

class Test(Tap):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.description = 'simple description'
    
    a: int = 1
    b: str = '1212'

print(Test().print_help())
```

It works for me with the following help info. I hope that can help you.

```shell
usage: ss.py [--a A] [--b B] [-h]

simple description

optional arguments:
  --a A       (int, default=1)
  --b B       (str, default=1212)
  -h, --help  show this help message and exit
```

***

BTW, I think there should be simple description for tap class, How do you think about it? @swansonk14  

```python
class Test(Tap):
    """simple description"""
    
    a: int = 1
    b: str = '1212'
```

I think this code is consisit with Tap, If it can, I have willing to contribute this feature.  @swansonk14

**Comment by martinjm97** [comment]
Hi @Moreh-LeeJunhyeok, 

Thank you for bringing this up and @wj-Mcat thank you for providing a slick solution.

There are now two different ways to set description. By default, the description is the docstring of the Tap class. Alternatively, it can be passed in as a keyword argument to the Tap object. The latter overrides the former. Here are two examples:
```python
from tap import Tap

class Args(Tap):
    """Simple description. """
    field: str = 'a'

args = Args().parse_args()
```

```python
from tap import Tap

class Args(Tap):
    field: str = 'a'

args = Args(description="Simple description.").parse_args()
```

Let us know if you have any further questions and happy tapping!

Best, 
Kyle and Jesse

**Comment by wj-Mcat** [comment]
@martinjm97  The above examples are so great and intuitive, so all of them should be supported in the tap. How dou you think about it ?

**Comment by martinjm97** [comment]
I believe they are supported by Tap as it currently is (though we have yet to push the latest version to PyPI).

**Comment by wj-Mcat** [comment]
Great to know that, let's get a happy tapping.
