### ISSUE TITLE
Semantics around positial arguments are weird

### ISSUE THREAD

**Issue by ShaneEverittM** [swansonk14/typed-argument-parser#79]
Currently if you make an argument positional as per the example, the help text does not specify required, and says that the default is `None`, which is not intuitive since positional arguments ARE required.
It currently looks like this:
```python
class Args(Tap):
    arg: str  # Some help text

    def configure(self):
        self.add_argument('arg')
```
which produces the following output:
```
usage: test-run.py [-h] arg

positional arguments:
  arg  (str, default=None) Some help text

optional arguments:
  -h, --help   show this help message and exit
```
I think it should produce:
```
usage: test-run.py [-h] arg

positional arguments:
  arg  (str, required) Some help text

optional arguments:
  -h, --help   show this help message and exit
```

**Comment by martinjm97** [comment]
Hi @ShaneEverittM, 

You're totally right! Thank you for raising this issue. We'll make changes as soon as we can. We think that the appropriate change would be at https://github.com/swansonk14/typed-argument-parser/blob/d1e4d50c1d1afaa849ed5640a389d86c021e45cf/tap/tap.py#L142. Feel free to submit a PR and write some tests as it will expedite the process. 

Thanks again, 
Kyle and Jesse
