### ISSUE TITLE
Tap does not recognise class variables when class is decorated 

### ISSUE THREAD

**Issue by TimRepke** [swansonk14/typed-argument-parser#80]
Hi,

I recently discovered this library and love using it. Thank you very much for all the effort of building it!

In a current project, I wanted to use `Tap` in a probably unconventional way, so that I don't have to change the rest of the project. I'm using it to expose dataclasses to the command line. It works fine in Python 3.8, but breaks in 3.10 (which I need to use).

This is a working example (in 3.8, that is):

```python
from tap import Tap
from typing import get_type_hints
from dataclasses import dataclass
from tap.utils import get_class_variables
from collections import OrderedDict

@dataclass
class TestA:
    a: str = 'd'  # Very helpful explanation
    b: int = 3


@dataclass
class TestB:
    c: bool = False  # Another help

sub_configs = {
    'a': TestA,
    'b': TestB,
}

class ProgrammaticArgumentParser(Tap):
    def configure(self):
        class_variables = []
        annotations = []
        for cls_name, cls in sub_configs.items():
            # append all class attributes, including annotations (e.g. comments)
            class_variables += [(f'{cls_name}_{var}', data)
                                for var, data in get_class_variables(cls).items()]

            # append all annotations (e.g. type hints)
            annotations += [(f'{cls_name}_{var}', data)
                            for var, data in get_type_hints(cls).items()]

            # transfer default parameters to this instance
            for var in get_type_hints(cls).keys():
                try:
                    setattr(self, f'{cls_name}_{var}', getattr(cls, var))
                except AttributeError:
                    # this attribute has no default value
                    pass

        # inject the gathered class variables and annotations to the tap instance
        self.class_variables = OrderedDict(class_variables)
        self._annotations = dict(annotations)

# parse command line arguments
args = ProgrammaticArgumentParser(underscores_to_dashes=True).parse_args()
print(args)
```

The problem originates in the `get_class_variables()` function. It does generate the expected return in Python 3.8, but returns an empty OrderedDict in 3.10. Looking closer, it turns out that with a decorator specified, the `get_class_column()` function returns `0`, which breaks the check for `token['start_column'] == class_variable_column`.

For example, the indentation of the first variable is 4 spaces, but it expects no indentation.
```
{'token_type': 1, 'token': 'a', 'start_line': 3, 'start_column': 4, 'end_line': 3, 'end_column': 5, 'line': "    a: str = 'd'  # Very helpful explanation\n"}
```
Unfortunately, I may have found the underlying issue, but I'm at a loss on how to fix it without breaking loads of stuff. Removing the decorator fixes Tap, but then I can't use the dataclass anymore.

So I came up with this fix, which moves the `first_line` ahead if it meets an `@` token.
https://github.com/swansonk14/typed-argument-parser/blob/main/tap/utils.py#L182
```python
def get_class_column(obj: type) -> int:
    """Determines the column number for class variables in a class."""
    first_line = 1
    for token_type, token, (start_line, start_column), (end_line, end_column), line in tokenize_source(obj):
        if token.strip() == '@':
            first_line += 1
        if start_line <= first_line or token.strip() == '':
            continue

        return start_column
```

**Comment by martinjm97** [comment]
Hi @TimRepke, 

Thank you for raising this fascinating issue and providing a detailed write-up. We'll think more about this soon. Feel free to make a PR and write a few tests as it will expedite the process for us.

Thanks again,
Kyle and Jesse

**Comment by martinjm97** [comment]
Thank you @TimRepke!
