### ISSUE TITLE
Feature request: 'inverse boolean' combined with different dest

### ISSUE THREAD

**Issue by ds-stevento** [swansonk14/typed-argument-parser#85]
I sometimes use the following pattern to enable some functonality by default but still allow disabling it:
```python
parser = ArgumentParser()
parser.add_argument('--skip-thingy', action='store_false', dest='do_thingy')

args = parser.parse_args(...)

if args.do_thingy:   # Easier to understand than `if not args.skip_thingy:`
   # ....

parser.parse_args('')   # Namespace(do_thingy=True)
parser.parse_args(['--skip-thingy'])  # Namespace(do_thingy=False)
```

Is it possible to do this with `Tap`? I have the sense Tap tries to accommodate this by allowing a default `True` value for a boolean argument but the way it's implemented right now doesn't make a lot of sense to me since the name of the argument cannot be updated to the inverse meaning, e.g.:

```python
class Args(Tap):
     do_thingy: bool = True   # Would default in a 'do_thingy' behavior

args = Args().parse_args('')   # Correct: do_thingy = true
args = Args().parse_args(['--do_thingy'])  # Correct according to the docs: do_thingy = false, but conceptually this doesn't make a lot of sense, I'd like to do something like '--skip-thingy' to make 'do_thingy' False
```

Any idea how I should go about doing that?

**Comment by swansonk14** [comment]
Hi @ds-steventondeur,

Thank you for raising this issue! `Tap` has a related feature to allow explicitly specifying boolean arguments, which we think can handle your use case well. See the example below.

```python
from tap import Tap

class Args(Tap):
     do_thingy: bool = True

# Set do_thingy to True by default
args = Args(explicit_bool=True).parse_args('')
print(args.do_thingy)  # True

# Set do_thingy to False
args = Args(explicit_bool=True).parse_args('--do_thingy False')
print(args.do_thingy)  # False
```

In the above example, `do_thingy` will be set to `True` by default but can be set to `False` by specifying `--do_thingy False`. Note that `do_thingy` can also be set to `True` or `False` with any capitalization of "True" or "False" as well as 1 or 0 (e.g. for `True`, you can use  `--arg tRu`, `--arg T`, or `--arg 1`).

Best,
Kyle and Jesse
