### ISSUE TITLE
Escaped characters in docstring are over-escaped by the tokenizer

### ISSUE THREAD

**Issue by martinjm97** [swansonk14/typed-argument-parser#97]
The branch [quote-docstrings](https://github.com/swansonk14/typed-argument-parser/tree/quote-docstrings) has a testcase that shows that `\"` is tokenized as `\\\"` by the tokenizer library. The branch also contains preliminary attempts to fix this issue.

**Comment by swansonk14** [comment]
This is fixed here: https://github.com/swansonk14/typed-argument-parser/pull/148
